//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("A Cellario Device Driver for hrb.templatedriver.serial, dev, 95bc815.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("4.0.0.0m-95bc815")]
[assembly: System.Reflection.AssemblyCompany("HighRes Biosolutions")]
[assembly: System.Reflection.AssemblyProduct("hrb.templatedriver.serial Cellario Driver")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2004-2023 HighRes Biosolutions")]
[assembly: System.Reflection.AssemblyFileVersion("4.0.0.0")]
[assembly: System.Reflection.AssemblyVersion("4.0.0.0")]
[assembly: System.Reflection.AssemblyTitle("hrb.templatedriver.serial Cellario Driver")]


